{
	"items": [
	{
		"track": {
			"album": {
				"album_type": "single",
				"artists": [
					{
						"external_urls": {
							"spotify": "https://open.spotify.com/artist/0PxzGnCYBpSuaI49OR94cA"
						},
						"href": "https://api.spotify.com/v1/artists/0PxzGnCYBpSuaI49OR94cA",
						"id": "0PxzGnCYBpSuaI49OR94cA",
						"name": "Big Wild",
						"type": "artist",
						"uri": "spotify:artist:0PxzGnCYBpSuaI49OR94cA"
					}
				],
				"available_markets": [
					"AD",
					"AR",
					"AT",
					"AU",
					"BE",
					"BG",
					"BO",
					"BR",
					"CA",
					"CH",
					"CL",
					"CO",
					"CR",
					"CY",
					"CZ",
					"DE",
					"DK",
					"DO",
					"EC",
					"EE",
					"ES",
					"FI",
					"FR",
					"GB",
					"GR",
					"GT",
					"HK",
					"HN",
					"HU",
					"ID",
					"IE",
					"IL",
					"IS",
					"IT",
					"JP",
					"LI",
					"LT",
					"LU",
					"LV",
					"MC",
					"MT",
					"MX",
					"MY",
					"NI",
					"NL",
					"NO",
					"NZ",
					"PA",
					"PE",
					"PH",
					"PL",
					"PT",
					"PY",
					"RO",
					"SE",
					"SG",
					"SK",
					"SV",
					"TH",
					"TR",
					"TW",
					"US",
					"UY",
					"VN",
					"ZA"
				],
				"external_urls": {
					"spotify": "https://open.spotify.com/album/0IQn4dKzcsFw1N0Xne5R6x"
				},
				"href": "https://api.spotify.com/v1/albums/0IQn4dKzcsFw1N0Xne5R6x",
				"id": "0IQn4dKzcsFw1N0Xne5R6x",
				"images": [
					{
						"height": 640,
						"url": "https://i.scdn.co/image/d6ffd4a467f96e77137f3cc93203ceb6b6b92079",
						"width": 640
					},
					{
						"height": 300,
						"url": "https://i.scdn.co/image/0b0cdc12bc8d8deabcbf7a25f01802c8e26456ad",
						"width": 300
					},
					{
						"height": 64,
						"url": "https://i.scdn.co/image/8459b386d4ecc9989feae8660bbf467aed012780",
						"width": 64
					}
				],
				"name": "Invincible EP",
				"release_date": "2017-02-10",
				"release_date_precision": "day",
				"type": "album",
				"uri": "spotify:album:0IQn4dKzcsFw1N0Xne5R6x"
			},
			"artists": [
				{
					"external_urls": {
						"spotify": "https://open.spotify.com/artist/0PxzGnCYBpSuaI49OR94cA"
					},
					"href": "https://api.spotify.com/v1/artists/0PxzGnCYBpSuaI49OR94cA",
					"id": "0PxzGnCYBpSuaI49OR94cA",
					"name": "Big Wild",
					"type": "artist",
					"uri": "spotify:artist:0PxzGnCYBpSuaI49OR94cA"
				}
			],
			"available_markets": [
				"AD",
				"AR",
				"AT",
				"AU",
				"BE",
				"BG",
				"BO",
				"BR",
				"CA",
				"CH",
				"CL",
				"CO",
				"CR",
				"CY",
				"CZ",
				"DE",
				"DK",
				"DO",
				"EC",
				"EE",
				"ES",
				"FI",
				"FR",
				"GB",
				"GR",
				"GT",
				"HK",
				"HN",
				"HU",
				"ID",
				"IE",
				"IL",
				"IS",
				"IT",
				"JP",
				"LI",
				"LT",
				"LU",
				"LV",
				"MC",
				"MT",
				"MX",
				"MY",
				"NI",
				"NL",
				"NO",
				"NZ",
				"PA",
				"PE",
				"PH",
				"PL",
				"PT",
				"PY",
				"RO",
				"SE",
				"SG",
				"SK",
				"SV",
				"TH",
				"TR",
				"TW",
				"US",
				"UY",
				"VN",
				"ZA"
			],
			"disc_number": 1,
			"duration_ms": 220000,
			"episode": false,
			"explicit": false,
			"external_ids": {
				"isrc": "USQY51706110"
			},
			"external_urls": {
				"spotify": "https://open.spotify.com/track/2sKTYRCgUHXmIhI2hoBuZE"
			},
			"href": "https://api.spotify.com/v1/tracks/2sKTYRCgUHXmIhI2hoBuZE",
			"id": "2sKTYRCgUHXmIhI2hoBuZE",
			"is_local": false,
			"name": "When I Get There",
			"popularity": 62,
			"preview_url": "https://p.scdn.co/mp3-preview/94da6c217673342dae81614340d4094e1e9d53a4?cid=774b29d4f13844c495f206cafdad9c86",
			"track": true,
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:2sKTYRCgUHXmIhI2hoBuZE"
		}
	}
]
}